"""imagine-to-3d AUTO: one command from existing Imagine images to a gated, phone-budgeted, staged object.
Every lesson of 2026-10-08..10 is a stage with a hard check; nothing ships on a FAIL and no stage ever generates an
Imagine image (missing / insufficient Imagine input -> NEEDS_IMAGINE + a request batch for imagine.py, not run).

  python3 auto.py run   spec.yaml [--stages a,b,...] [--from stage]     # run (skips stages whose outputs are fresh)
  python3 auto.py plan  spec.yaml                                         # print the stage plan + what is manual
  python3 auto.py report WORK                                             # REPORT.md from state.json

Stages (order; each writes WORK/<stage>.json and updates WORK/state.json):
  inputs    Imagine inputs exist, native size (no upscale, no stretch > 1.25), provenance; near-duplicate plates grouped
  classify  type from the key crop (classify.py) unless spec.type is set
  shape     hull -> fused DA-V2 depth (cross-view consistency) -> per-plate depth relief (run.py strata stages)
  geometry  CONTINUOUS strata/surfaces (strata2.py: one wall per section, joint-blended plate windows, smooth welded
            normals, rotated/toned fallen blocks) + shape-seed search to outline IoU >= iouMin and window salts until
            no repetition (gen_strata_all.py, GEN=strata2.py). Same shell at every LOD, relief as an attribute.
  pack      int16 + index + gzip, LOD2 dropped, LOD0 on demand, gen-summary.json copied (pack_strata.py)
  detail    tiling Imagine detail layer (~512 px/m, hex 3-tap, DA-V2 normals) from EXISTING seamless Imagine crops
            (detail/bake_detail.py) + texture-space no-repetition check (detail/repeat_check.py) -> detail.json
  grade     offline grading of section plates with the runtime's own functions -> R8 brightness atlases + low-res chroma
  stage     copy packed geometry / atlases / detail into the STAGING dir (refuses the live tree)
  shaders   dump the staging page's fragment shaders (checks/dump-shaders.mjs)      [browser]
  perf      per-object budget at the full pixel ratio (checks/perf_budget.py)
  morph     approach-morph 300 -> 10 -> 300 m, camera outside the collision hull (checks/approach-morph.mjs) [browser]
  gate      object-gate CLI (PR #191 thresholds) on the staging page, zero FAIL; FAIL -> fixloop.py plan      [browser]
  report    REPORT.md: every row, what passed, what needs Imagine, what is still manual
"""
import argparse, glob, json, os, shutil, subprocess, sys, time
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import i23d_common as C
PY = sys.executable
STAGES = ["inputs", "classify", "shape", "geometry", "pack", "detail", "grade", "stage", "shaders", "perf", "morph", "gate", "report"]
BROWSER = {"shaders", "morph", "gate"}
LIVE_GUARD = [os.environ.get("I23D_LIVE_ROOT", "/workspace/zb-preview-1008")]   # files the live page loads live here
MANUAL = {   # honest list, printed in every plan/report
    "imagine": "New Imagine images (views, wall plates, detail crops) are never generated by this tool: it writes the request batch, a human/agent runs imagine.py with approval.",
    "mount": "First mount of a NEW object type into the game page (one import + one call in the biome main module) is a code change reviewed by hand; afterwards the staging page reloads the assets by itself.",
    "swap": "Staging -> live swap + ?v bump stays a human decision after the report (gate PASS is required, not sufficient).",
    "phone": "Real-phone fps (S20 FE) is measured by SmiR; the box has no GPU (SwiftShader timings are relative only).",
    "checklist": "Key checklist items need a Grok-vision or owner pass record (object-gate records/); NEEDS_REVIEW otherwise.",
}


def sh(*a, env=None, check=False, timeout=None):
    print("+", " ".join(map(str, a)), flush=True)
    r = subprocess.run([str(x) for x in a], env=dict(os.environ, **(env or {})), capture_output=True, text=True, timeout=timeout)
    if check and r.returncode: raise RuntimeError(f"{a[1] if len(a) > 1 else a[0]} exit {r.returncode}: {r.stderr[-800:]}")
    return r


class Run:
    def __init__(self, spec_path):
        self.spec = C.read_yaml(spec_path); self.spec_path = os.path.abspath(spec_path)
        self.work = self.spec["work"]; os.makedirs(self.work, exist_ok=True)
        self.sp = os.path.join(self.work, "state.json")
        self.state = json.load(open(self.sp)) if os.path.exists(self.sp) else dict(object=self.spec["object"], stages={})
        self.type = self.spec.get("type", "auto")

    def save(self): C.dump(self.state, self.sp)

    def done(self, name, status, **kw):
        rec = dict(status=status, at=time.strftime("%Y-%m-%d %H:%M:%S"), **kw)
        self.state["stages"][name] = rec; C.dump(rec, os.path.join(self.work, f"{name}.json")); self.save()
        print(f"[{name}] {status}", {k: v for k, v in kw.items() if k in ("summary", "reason")}, flush=True)
        return rec

    # ---------------------------------------------------------------- stages
    def s_inputs(self):
        sp = self.spec; im = sp.get("imagine", {}); bad, info = [], []
        files = []
        for k, v in (im.get("views") or {}).items(): files.append(("view", k, v))
        if im.get("plates"):
            pj = json.load(open(im["plates"]))
            walls = set(pj.get("walls", []))
            for w, p in pj.get("imagine", {}).items(): files.append(("plate" if (w in walls or not walls) else "plate-unused", w, p))
        for p in sorted(glob.glob(os.path.join(im.get("detailSrc", "/nonexistent"), "*.png"))): files.append(("detail", os.path.basename(p), p))
        for p in im.get("sectionTex", []): files.append(("section", os.path.basename(p), os.path.join(im.get("sectionTexDir", ""), p)))
        raw = sorted(glob.glob(os.path.join((sp.get("grade") or {}).get("rawDir") or "/nonexistent", "raw*.rgba")))
        for p in raw:   # decoded Imagine section cells: must be exactly 1024² (never resized)
            if os.path.getsize(p) != 1024 * 1024 * 4: bad.append(dict(kind="section-raw", id=os.path.basename(p), why="not a 1024² RGBA cell"))
            info.append(dict(kind="section-raw", id=os.path.basename(p), size=[1024, 1024], native=True))
        from PIL import Image
        natives = set(C.IMAGINE_NATIVE.values()) | {(1376, 752), (752, 1376)}
        for kind, k, p in files:
            if not os.path.exists(p): bad.append(dict(kind=kind, id=k, path=p, why="missing")); continue
            w, h = Image.open(p).size
            native = (w, h) in natives
            crop = not native and w <= 1376 and h <= 1376          # recorded crops of a native image (e.g. 928² seamless interior)
            if not native and not crop: bad.append(dict(kind=kind, id=k, path=p, size=[w, h], why="larger than any Imagine native size (upscaled?)"))
            info.append(dict(kind=kind, id=k, size=[w, h], native=native))
        groups = self.plate_groups(files)
        distinct = len(set(groups.values())) if groups else 0
        need = int(sp.get("geometry", {}).get("minDistinctWallPlates", 0))
        req = None
        if need and distinct < need:
            req = self.imagine_requests(need - distinct, files)
        st = "FAIL" if bad else ("NEEDS_IMAGINE" if req else "PASS")
        return self.done("inputs", st, files=len(files) + len(raw), bad=bad, plateGroups=groups, distinctWallPlates=distinct, minDistinct=need,
                         imagineBatch=req, summary=f"{len(files) + len(raw)} Imagine files, {len(bad)} bad, {distinct} distinct wall plates (need {need})")

    def plate_groups(self, files):
        from PIL import Image
        ex = set(self.spec.get("imagine", {}).get("excludePlates", []))
        ps = [(k, p) for kind, k, p in files if kind == "plate" and os.path.exists(p) and k.startswith("w") and k not in ex]
        A = {k: np.asarray(Image.open(p).convert("L").resize((320, 180)), float).ravel() for k, p in ps}
        g = {}
        for i, (k, _) in enumerate(ps):
            g[k] = k
            for k2, _ in ps[:i]:
                if np.corrcoef(A[k], A[k2])[0, 1] > 0.9: g[k] = g[k2]; break
        return g

    def imagine_requests(self, n, files):
        """write (never run) an Imagine request batch for n new distinct wall plates, refs = key crop + one existing plate."""
        from imagine import Request, write_batch
        crop = self.spec["crop"]; plates = [p for kind, k, p in files if kind == "plate" and k.startswith("w")]
        reqs = [Request(id=f"wall-new-{i + 1}", kind="edit", aspect="16:9", refs=[crop, plates[i % len(plates)]],
                        prompt=("<IMAGE_1> rock: a NEW straight-on 16 m wide section of the same sandstone cliff wall, same light and colours as "
                                "<IMAGE_2> but a clearly different bedding / fracture / erosion pattern (no brick grid, no repeated blocks), fills the frame, "
                                "no sky, no ground, no text."), out=os.path.join(self.work, "imagine-req", f"wall-new-{i + 1}.jpg"),
                        purpose="distinct wall plate for the no-repetition rule")
                for i in range(n)]
        os.makedirs(os.path.join(self.work, "imagine-req"), exist_ok=True)
        return write_batch(reqs, os.path.join(self.work, "imagine-req", "batch-walls.json"), note="auto.py NEEDS_IMAGINE (not run; needs approval)")

    def s_classify(self):
        if self.type != "auto": return self.done("classify", "SKIP", type=self.type, summary=f"type fixed by spec: {self.type}")
        import classify
        r = classify.classify(self.spec["crop"], height_m=self.spec.get("heightM"), work=self.work)
        self.type = r["type"]; self.state["type"] = self.type
        return self.done("classify", "NEEDS_REVIEW" if r["needsVision"] else "PASS", type=r["type"], margin=r["margin"], summary=f"type {r['type']} margin {r['margin']}")

    def s_shape(self):
        if not self.spec.get("geometry"): return self.done("shape", "SKIP", summary="no geometry in spec")
        g = self.spec["geometry"]; pre = g["hull"]; fused = g.get("fusedHull", pre + "F")
        if g.get("reuseShape") and os.path.exists(fused + "-H.npy"):
            fz = json.load(open(fused + "-fuse-report.json")) if os.path.exists(fused + "-fuse-report.json") else {}
            ok = fz.get("consistency", {}).get("ok")
            return self.done("shape", "PASS" if ok else "FAIL", reused=fused, consistency=fz.get("consistency"),
                             summary=f"reused fused hull {os.path.basename(fused)}, consistency {fz.get('consistency')}")
        views = g["viewsJson"]; secs = json.load(open(g["sectionsJson"]))
        sh(PY, f"{HERE}/hull.py", "--plates", views, "--out", pre, "--height", self.spec["heightM"], check=True)
        sh(PY, f"{HERE}/fuse.py", pre, views, pre + "F", check=True)
        fz = json.load(open(pre + "F-fuse-report.json"))
        if not fz["consistency"]["ok"]: return self.done("shape", "FAIL", consistency=fz["consistency"], reason="depth fusion cross-view consistency")
        sh(PY, f"{HERE}/depth_relief.py", self.type, g.get("pxm", 80), g["reliefDir"], *[secs[k] for k in secs["walls"]], check=True)
        return self.done("shape", "PASS", consistency=fz["consistency"], summary="hull + fused depth + relief")

    def s_geometry(self):
        if not self.spec.get("geometry"): return self.done("geometry", "SKIP", summary="no geometry in spec")
        g = self.spec["geometry"]; out = os.path.join(self.work, "geo-raw")
        rows = []
        if g.get("reuseGeometry"):
            out = g["reuseGeometry"]
        else:
            os.makedirs(out, exist_ok=True)
            env = dict(GEN="strata2.py", HULL=os.path.basename(g.get("fusedHull", g["hull"] + "F")), RELIEF_DIR=g["reliefDir"], KEY_CROP=self.spec["crop"],
                       IOU_MIN=str(g.get("iouMin", 0.87)), PLACEMENTS=json.dumps(g["placements"]), MAX_SEEDS=str(g.get("maxSeeds", 10)),
                       SALTS=str(g.get("salts", 16)), MIN_PXM=str(g.get("minPxPerM", 64)), MAX_STRETCH=str(g.get("maxStretch", 1.3)),
                       PLATES_JSON=self.spec["imagine"]["plates"])
            sh(PY, f"{HERE}/gen_strata_all.py", os.path.dirname(g["hull"]), self.spec["imagine"]["views"]["front"], self.spec["imagine"]["views"]["top"], out, env=env, check=True)
        iou = {}
        if self.spec.get("crop"):
            r = sh(PY, f"{HERE}/outline_iou.py", self.spec["crop"], *[os.path.join(out, p[0]) for p in g["placements"]])
            try: iou = {os.path.basename(k): v["iou"] for k, v in json.loads(r.stdout.strip().splitlines()[-1]).items()}
            except Exception: iou = {}
        lim = dict(iou=g.get("iouMin", 0.87), pxm=g.get("minPxPerM", 64), stretch=g.get("maxStretch", 1.3))
        n = lambda v: sum(v.values()) if isinstance(v, dict) else (v or 0)
        for pid, sc in g["placements"]:
            d = json.load(open(os.path.join(out, f"{pid}-geo.json")))
            L = d["lods"]; st = [l["stretch"] for l in L]
            row = dict(id=pid, method=d.get("method"), sameShell=all(s.get("sameShell", False) for s in st) or d.get("lodMode", "").startswith("same-shell"),
                       iou=iou.get(pid), clashGroups=n(d.get("repeatClashGroups", d.get("repeatClash"))), adjGroups=n(d.get("adjSameGroup", d.get("adjSamePlate"))),
                       minPxPerM=round(min(s["minPxPerM"] for s in st), 1), p01PxPerM=round(min(s.get("p01PxPerM", s["minPxPerM"]) for s in st), 1),
                       maxStretch=round(max(s["maxStretch"] for s in st), 3), blendMaxStretch=round(max(s.get("blendMaxStretch", s["maxStretch"]) for s in st), 3),
                       nonManifold=sum(s.get("nonManifoldEdges", 0) for s in st), relief=any(s.get("relief") for s in st), tris=[l["tris"] for l in L])
            row["fails"] = [k for k, bad in (("continuous", row["method"] != "continuous-strata-v10"), ("sameShellLOD", not row["sameShell"]),
                                             ("outlineIoU", row["iou"] is not None and row["iou"] < lim["iou"]), ("repetition", row["clashGroups"] > 0),
                                             ("neighbours", row["adjGroups"] > 0), ("pxPerM", row["minPxPerM"] < lim["pxm"]),
                                             ("stretch", row["maxStretch"] > lim["stretch"]), ("nonManifold", row["nonManifold"] > 0), ("relief", not row["relief"])) if bad]
            rows.append(row)
        fails = sorted({f for r in rows for f in r["fails"]})
        st = "PASS" if not fails else ("NEEDS_IMAGINE" if set(fails) <= {"repetition", "neighbours"} and self.state["stages"].get("inputs", {}).get("imagineBatch") else "FAIL")
        return self.done("geometry", st, dir=out, rows=rows, failRows=fails, limits=lim,
                         summary=f"{len(rows)} placements, failing rows: {fails or 'none'}")

    def s_pack(self):
        if not self.spec.get("geometry"): return self.done("pack", "SKIP", summary="no geometry in spec")
        src = self.state["stages"]["geometry"]["dir"]; dst = os.path.join(self.work, "geo-packed")
        ids = [p[0] for p in self.spec["geometry"]["placements"]]
        if self.spec["geometry"].get("reusePacked"):
            dst = self.spec["geometry"]["reusePacked"]
        else:
            sh(PY, f"{HERE}/pack_strata.py", src, dst, *ids, check=True)
        ok = os.path.exists(os.path.join(dst, "gen-summary.json")) and all(os.path.exists(os.path.join(dst, f"{i}-lod0.bin.gz")) for i in ids)
        return self.done("pack", "PASS" if ok else "FAIL", dir=dst, summary="int16 + gzip, LOD0 on demand" + ("" if ok else " (gen-summary or .gz missing)"))

    def s_detail(self):
        d = self.spec.get("detail");
        if not d: return self.done("detail", "SKIP", summary="no detail layer in spec")
        out = os.path.join(self.work, "detail"); os.makedirs(out, exist_ok=True)
        sl = os.path.join(out, "slices.json"); json.dump(d["slices"], open(sl, "w"))
        sh(PY, f"{HERE}/detail/bake_detail.py", out, "--src", self.spec["imagine"]["detailSrc"], "--slices", sl, "--pxm", d.get("pxPerM", 512), check=True)
        rep = json.load(open(os.path.join(out, "bake-report.json"))); rows = []
        for name in rep["slices"]:
            r = sh(PY, f"{HERE}/detail/repeat_check.py", os.path.join(out, f"gdet-{name}.jpg"), d.get("rotDeg", 180), check=True)
            rc = json.loads(r.stdout.strip().splitlines()[-1]); s = rep["slices"][name]
            ok = rc["hexTiling"]["latticePeakMax"] <= max(0.05, rc["hexTiling"]["bgP99"]) and s["seamStepRatioX"] <= 1.5 and s["seamStepRatioY"] <= 1.5 \
                 and rc["stdHex"] >= 0.8 * rc["stdPlain"]
            rows.append(dict(slice=name, tileM=s["tileM"], pxPerM=rep["pxPerM"], latticePeakHex=rc["hexTiling"]["latticePeakMax"], latticePeakPlain=rc["plainTiling"]["latticePeakMax"],
                             bgP99=rc["hexTiling"]["bgP99"], contrastKept=round(rc["stdHex"] / max(rc["stdPlain"], 1e-6), 2), seam=[s["seamStepRatioX"], s["seamStepRatioY"]], ok=ok))
        cfg = dict(enabled=True, tileM=rows[0]["tileM"] if rows else 1.8125, nearM=d.get("nearM", 15), farM=d.get("farM", 30), pxPerM=rep["pxPerM"],
                   rotDeg=d.get("rotDeg", 180), lum=d.get("lum", 0.8), nrm=d.get("nrm", 0.9), slices=[r["slice"] for r in rows], surfaceOnly=True,
                   runtime="runtime/detail-chunk.js (objects) / detail/make_runtime_gd.py (ground)")
        C.dump(cfg, os.path.join(out, "detail.json"))
        return self.done("detail", "PASS" if rows and all(r["ok"] for r in rows) else "FAIL", rows=rows, config=os.path.join(out, "detail.json"),
                         summary=f"{len(rows)} slices at {rep['pxPerM']} px/m, hex lattice peaks {[r['latticePeakHex'] for r in rows]}")

    def s_grade(self):
        g = self.spec.get("grade")
        if not g: return self.done("grade", "SKIP", summary="no section atlas in spec")
        w = os.path.join(self.work, "grade"); os.makedirs(w, exist_ok=True)
        if g.get("rawDir"):
            for f in glob.glob(os.path.join(g["rawDir"], "raw*.rgba")): shutil.copy(f, w)
        else:
            subprocess.run([PY, f"{HERE}/grade/decode.py", json.dumps(self.spec["imagine"]["sectionTex"]), self.spec["imagine"]["sectionTexDir"], w], check=True)
        subprocess.run(["node", f"{HERE}/grade/grade.mjs", g["runtimeModule"]], cwd=w, check=True)
        subprocess.run([PY, f"{HERE}/grade/atlas.py", os.path.join(w, "sec"), str(len(glob.glob(os.path.join(w, 'raw*.rgba'))))], cwd=w, check=True)
        de = json.load(open(os.path.join(w, "recon-de.json")))
        ok = de["dEmean"] <= g.get("dEmeanMax", 1.0) and de["dEp99worst"] <= g.get("dEp99Max", 6.0)
        same = None
        if g.get("compareTo"):
            from PIL import Image
            same = all(os.path.exists(os.path.join(g["compareTo"], f)) and np.array_equal(np.asarray(Image.open(os.path.join(w, "sec", f))), np.asarray(Image.open(os.path.join(g["compareTo"], f))))
                       for f in os.listdir(os.path.join(w, "sec")))
        mib = sum(C_tex_mib(p) for p in glob.glob(os.path.join(w, "sec", "*.png")))
        return self.done("grade", "PASS" if ok else "FAIL", dir=os.path.join(w, "sec"), dE=de, gpuMiB=round(mib, 1), identicalToReference=same,
                         summary=f"R8 luma + chroma atlases {round(mib, 1)} MiB, dE mean {de['dEmean']:.2f} p99 {de['dEp99worst']:.2f}")

    def s_stage(self):
        dst = self.spec.get("staging")
        if not dst: return self.done("stage", "SKIP", summary="no staging dir in spec")
        dst = os.path.abspath(dst)
        for live in LIVE_GUARD:
            if dst.rstrip("/") == os.path.abspath(live).rstrip("/"): return self.done("stage", "FAIL", reason=f"staging dir IS the live root {live}")
        mk = os.path.join(dst, ".i23d-staging")
        if os.path.exists(dst) and os.listdir(dst) and not os.path.exists(mk):
            return self.done("stage", "FAIL", reason=f"{dst} exists and is not an imagine-to-3d staging dir (no marker): never write into live/foreign folders")
        os.makedirs(dst, exist_ok=True); open(mk, "w").write("imagine-to-3d auto staging output; the live page must not load this folder\n")
        S = self.state["stages"]; copied = []
        for key, sub in (("pack", "geo"), ("grade", "sec"), ("detail", "detail")):
            d = S.get(key, {}).get("dir") or (os.path.dirname(S[key]["config"]) if S.get(key, {}).get("config") else None)
            if not d or not os.path.isdir(d): continue
            t = os.path.join(dst, sub); shutil.rmtree(t, ignore_errors=True)
            shutil.copytree(d, t, ignore=shutil.ignore_patterns("*.log", "slices.json")); copied.append(sub)
        return self.done("stage", "PASS", dir=dst, copied=copied, summary=f"staged {copied} -> {dst}")

    def s_shaders(self):
        u = self.spec.get("stagingUrl")
        if not u: return self.done("shaders", "MANUAL", summary="no stagingUrl (the object is not mounted on a staging page yet)")
        out = os.path.join(self.work, "shaders")
        r = sh("node", f"{HERE}/checks/dump-shaders.mjs", u, out, self.spec.get("shaderMatch", ""), timeout=1800)
        files = [os.path.join(out, x["file"]) for x in json.load(open(os.path.join(out, "fs-index.json")))] if r.returncode == 0 else []
        return self.done("shaders", "PASS" if files else "FAIL", files=files, summary=f"{len(files)} fragment shaders")

    def s_perf(self):
        from checks.perf_budget import run as perf
        S = self.state["stages"]
        tex = glob.glob(os.path.join(S.get("grade", {}).get("dir") or "/nonexistent", "*.png"))
        tex += glob.glob(os.path.join(os.path.dirname(S.get("detail", {}).get("config") or "/nonexistent/x"), "gdet-*.jpg"))
        tex += self.spec.get("perf", {}).get("extraTex", [])
        frag = S.get("shaders", {}).get("files") or self.spec.get("perf", {}).get("frag", [])
        r = perf(self.type if self.type != "auto" else "rock", S.get("pack", {}).get("dir"), tex, frag, self.spec.get("perf", {}).get("probe"),
                 os.path.join(self.work, "perf-report.json"))
        return self.done("perf", r["verdict"], rows=r["rows"], summary="; ".join(f"{x['check']}={x['value']} {x['status']}" for x in r["rows"]))

    def s_morph(self):
        u = self.spec.get("stagingUrl"); m = self.spec.get("morph", {})
        if not u: return self.done("morph", "MANUAL", summary="no stagingUrl")
        res = []
        for pid, heading in m.get("targets", []):
            out = os.path.join(self.work, "morph", pid)
            sh("node", f"{HERE}/checks/approach-morph.mjs", u, pid, heading, out, m.get("farM", 300), m.get("nearM", 10), timeout=7200)
            r = sh(PY, f"{HERE}/checks/morph_iou.py", out); res.append(json.loads(r.stdout.strip().splitlines()[-1]) if r.returncode == 0 else dict(dir=out, verdict="FAIL", error=r.stderr[-300:]))
        st = "PASS" if res and all(x["verdict"] == "PASS" for x in res) else ("FAIL" if res else "SKIP")
        return self.done("morph", st, runs=res, summary=f"{len(res)} approach runs: {[x['verdict'] for x in res]}")

    def s_gate(self):
        g = self.spec.get("gate")
        if not g or not self.spec.get("stagingUrl"): return self.done("gate", "MANUAL", summary="no gate scene / stagingUrl")
        out = os.path.join(self.work, "gate"); cli = os.path.join(C.OBJECT_GATE_DIR, "cli.mjs")
        r = sh("node", cli, "--scene", g["scene"], "--only", g["object"], "--out", out, timeout=14400)
        st = {0: "PASS", 1: "FAIL"}.get(r.returncode, "ERROR")
        fix = None
        if st == "FAIL" and os.path.exists(os.path.join(out, "fix-plan.json")):
            import fixloop
            fix = fixloop.plan(gate_plan=os.path.join(out, "fix-plan.json"), obj_type=self.type, out=os.path.join(out, "actions.json"))
        return self.done("gate", st, dir=out, fixActions=[(a["action"], a["failure"]["key"]) for a in (fix or {}).get("actions", [])],
                         summary=f"object-gate exit {r.returncode}")

    def s_report(self):
        S = self.state["stages"]; L = [f"# imagine-to-3d auto report: {self.spec['object']} ({self.state.get('type', self.type)})", "",
                                     f"spec `{self.spec_path}`, work `{self.work}`", "", "| stage | status | summary |", "|---|---|---|"]
        for s in STAGES[:-1]:
            if s in S: L.append(f"| {s} | **{S[s]['status']}** | {str(S[s].get('summary', S[s].get('reason', ''))).replace('|', '/')} |")
        geo = S.get("geometry", {}).get("rows", [])
        if geo:
            L += ["", "## geometry rows", "", "| id | IoU | clash groups | adj groups | min px/m | max stretch | non-manifold | tris | fails |", "|---|---|---|---|---|---|---|---|---|"]
            L += [f"| {r['id']} | {r['iou']} | {r['clashGroups']} | {r['adjGroups']} | {r['minPxPerM']} | {r['maxStretch']} | {r['nonManifold']} | {r['tris']} | {', '.join(r['fails']) or '-'} |" for r in geo]
        blocking = [s for s in STAGES[:-1] if S.get(s, {}).get("status") in ("FAIL", "ERROR", "NEEDS_IMAGINE", "NEEDS_REVIEW", "MANUAL")]
        L += ["", f"**Verdict: {'SHIP-READY (still needs the human swap)' if not blocking else 'NOT READY'}**" + (f" (blocking: {', '.join(blocking)})" if blocking else ""),
              "", "## still manual", ""] + [f"- **{k}**: {v}" for k, v in MANUAL.items()]
        if S.get("inputs", {}).get("imagineBatch"): L += ["", f"Imagine request batch written (NOT run): `{S['inputs']['imagineBatch']}`"]
        open(os.path.join(self.work, "REPORT.md"), "w").write("\n".join(L) + "\n")
        return self.done("report", "PASS", path=os.path.join(self.work, "REPORT.md"), blocking=blocking, summary=f"blocking: {blocking}")


def C_tex_mib(p):
    from PIL import Image
    im = Image.open(p); w, h = im.size
    return w * h * (1 if im.mode in ("L", "P") else 4) * 4 / 3 / 2**20


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("cmd", choices=["run", "plan", "report"]); ap.add_argument("target")
    ap.add_argument("--stages"); ap.add_argument("--from", dest="frm"); ap.add_argument("--no-browser", action="store_true")
    a = ap.parse_args()
    if a.cmd == "plan":
        R = Run(a.target); print("stages:", " -> ".join(STAGES)); print("browser stages:", sorted(BROWSER))
        for k, v in MANUAL.items(): print(f"manual[{k}]: {v}")
        return
    if a.cmd == "report":
        st = json.load(open(os.path.join(a.target, "state.json"))); print(json.dumps({k: v["status"] for k, v in st["stages"].items()}, indent=1)); return
    R = Run(a.target)
    todo = a.stages.split(",") if a.stages else STAGES[STAGES.index(a.frm):] if a.frm else STAGES
    for s in todo:
        if a.no_browser and s in BROWSER: R.done(s, "MANUAL", summary="skipped (--no-browser)"); continue
        try: rec = getattr(R, "s_" + s)()
        except Exception as e:
            rec = R.done(s, "ERROR", reason=f"{type(e).__name__}: {e}"[:600])
        if rec["status"] in ("FAIL", "ERROR") and s in ("inputs", "shape", "pack", "stage"):
            print(f"stop: {s} {rec['status']}"); R.s_report(); sys.exit(1)
    blocking = R.state["stages"]["report"].get("blocking", []) if "report" in R.state["stages"] else []
    sys.exit(0 if not blocking else 1)


if __name__ == "__main__":
    main()
