/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiVisionsRouteImport } from './routes/api/visions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionsRoute = ApiVisionsRouteImport.update({
  id: '/api/visions',
  path: '/api/visions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bot': typeof ApiBotRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/visions': typeof ApiVisionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bot': typeof ApiBotRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/visions': typeof ApiVisionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bot': typeof ApiBotRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/visions': typeof ApiVisionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/bot' | '/api/rtc' | '/api/visions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/bot' | '/api/rtc' | '/api/visions'
  id: '__root__' | '/' | '/api/bot' | '/api/rtc' | '/api/visions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBotRoute: typeof ApiBotRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiVisionsRoute: typeof ApiVisionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visions': {
      id: '/api/visions'
      path: '/api/visions'
      fullPath: '/api/visions'
      preLoaderRoute: typeof ApiVisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBotRoute: ApiBotRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiVisionsRoute: ApiVisionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
